routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/','login');
Auth::routes();
Route::group(['as' => 'user.', 'namespace' => 'User', 'middleware' => 'auth'], function () {

    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/logout', 'HomeController@logout')->name('logout');
    Route::any('/post/comment/Add', 'PostCommentsDataController@addcomments')->name('commentsADD');
    Route::resource('post', 'PostController');
    Route::post('post/add', 'PostController@store')->name('poststore');

    Route::resource('comments', 'CommentsController');

    Route::post('post/add/replli', 'PostCommentsDataController@repllieadd')->name('repllieaddurl');


});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

}

app/Http/Controllers/User/CommentsController.php
<?php

namespace App\Http\Controllers\User;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CommentsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        dd(1);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/User/HomeController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Models\Post;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $post=Post::orderBy('id', 'DESC')->get();
        return view('home',compact('post'));
    }
    public function logout()
    {
        auth()->logout();
        return view('login');
    }
}

app/Http/Controllers/User/PostCommentsDataController.php
<?php

namespace App\Http\Controllers\User;

use App\Models\PostComentsReply;
use App\Models\PostComments;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class PostCommentsDataController extends Controller
{
    public function addcomments(Request $request){
        if ($request->comment_id==null) {
            $comments = PostComments::create([
                'user_id' => Auth::user()->id,
                'post_id' => $request->post_id,
                'title' => $request->comment,
            ]);
        }
        return back();
    }

    public function repllieadd(Request $request)
    {

        if ($request->comment_id!=null){
            $comments= PostComentsReply::create([
                'user_id'=>Auth::user()->id,
                'post_id'=>$request->post_id,
                'comment_id'=>$request->comment_id,
                'title'=>$request->comment,

            ]);
        }

        return back();

    }
}

app/Http/Controllers/User/PostController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Requests\PostRequest;
use App\Models\Post;
use App\Models\PostComentsReply;
use App\Models\PostComments;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PostRequest $request)
    {


        if ($request->has('images')) {
            $pah=public_path('/post/'.date("Y") .'/'.date("m"));
            $photos = $request->file('images');
            if(!file_exists($pah)>0):
                if(!is_dir($pah.date("Y").'/'.date("m") )) {
                    mkdir($pah, 0755, true);
                }endif;
            $imageName =date("Y") .'/'.date("m").'/'.rand(1, 999999999999).'.'. $request->images->getClientOriginalExtension();
            $request->images->move(public_path('post/'. date("Y") . '/' . date("m") . '/'), $imageName);
           Post::create([
                'title'=>$request->title,
                'description'=>$request->description,
                'user_id'=>Auth::user()->id,
                'images'=>'/post/'.$imageName,
            ]);
        }else{
            Post::create([
                'title'=>$request->title,
                'description'=>$request->description,
                'user_id'=>Auth::user()->id,

            ]);
        }

return back()->with('succses','thenks add you posting');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $posts=Post::find($id);
        $comments=PostComments::with('CommentsReply')->where('post_id',$id)->get();;
        return view('user.showPosting',compact('comments','posts','id'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/user/showPosting.blade.php
@extends('layouts.app')
@section('content')
    <section id="blog-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">


                    <aside>
                        <img src="{{asset($posts->images)}}" class="img-responsive" style="height: 200px">
                        <div class="content-title">
                            <div class="text-center">
                                <h3><a href="#">{{$posts->title}}</a></h3>
                            </div>
                        </div>

                        <div class="content-footer">
                            <img class="user-small-img" src="
                                        {{asset('asset/logo/images.jpg')}}">
                            <span style="font-size: 16px;color: #fff;"></span>
                            <span class="pull-right"></span>

                        </div>
                    </aside>
                    <p>{{$posts->description}}</p>
                </div>
            </div>
        </div>

        <div class="container-fluid">
            <ul class="comments-list">
                @foreach($comments as $comment)
                    <li class="comment">
                        <a class="" href="#">
                            {{$comment->usercommentname->name}}
                        </a>
                        <div class="comment-body">
                            <div class="comment-heading">
                                <h4> {{$comment->title}}</h4>
                                <h5 class="time">{{$comment->created_at}}</h5>
                            </div>
                            <a href="#" class="btn btn-default stat-item">
                                <i class="fa fa-share icon"></i>{{count($comment->CommentsReply)}}
                            </a>
                        </div>
                        <ul class="comments-list">
                            @foreach($comment->CommentsReply as $commentsreply)

                                <li class="comment-{{$comment->id}}">
                                    <a class="" href="#">
                                        {{$commentsreply->userpost->name}}
                                    </a>
                                    <div class="comment-body">
                                        <div class="comment-heading">
                                            <h4 class="user">{{$commentsreply->title}}</h4>
                                        </div>
                                    </div>
                                </li>
                            @endforeach
                            <form method="post" action="{{route('user.repllieaddurl')}}">
                                @csrf
                                <input class="form-control comentinput" name="comment" placeholder="Add a comment"
                                       type="text">
                                <input type="hidden" value="{{$id}}" class="form-control" name="post_id">
                                <input type="hidden" value="{{$comment->id}}" class="form-control" name="comment_id">
                                <span class="input-group-addon">
                        <button type="submit"><i class="fa fa-plus"></i></button>
                    </span>
                            </form>
                        </ul>
                    </li>
                @endforeach
            </ul>
        </div>


        <form class="commentform" method="post" action="{{route('user.commentsADD')}}">
            @csrf
            <input class="form-control comentinput" name="comment" placeholder="Add a comment" type="text">
            <input type="hidden" value="{{$id}}" class="form-control" name="post_id">
            <input type="hidden" value="{{null}}" class="form-control" name="comment_id">
            <span class="input-group-addon">

         <button type="submit"><i class="fa fa-plus"></i></button>
        </span>
        </form>
    </section>

@endsection